---
title: "juvenile fish"
author: "Jorn School"
date: "27 oktober 2020"
output: word_document
---

```{r setup, include=FALSE}
rm(list=ls(all=T))

knitr::opts_chunk$set(
  echo = FALSE,
	message = FALSE,
	warning = FALSE,
	fig.fullwidth= TRUE,
	out.height = '100%',
	out.width = "100%",
	comment = NA,
  fig.align = 'center'
)
```



```{r, echo=FALSE, warning = FALSE, message = FALSE, include= FALSE}
library(rmarkdown)
library(pander)
library(knitr)
library(pander)        # tables
library(gridExtra)     # getting two ggplots in one plot
library(tidyverse)     # combined package of dplyr, tidyr, ggplot, readr, purrr and tibble
library(lubridate)     # data handling
library(reshape2)      # reshaping data; e.g. cast
library(readxl)        # excel reader
library(broom)         # clean up statistics
library(scales)        # pretty scales
library(stringr)       # string manipulations
library(RColorBrewer)  # colour scheme
library(viridis)
```

```{r, echo=FALSE, warning = FALSE, message = FALSE, include= FALSE}
## making the path to load the excelfile
onedrive <- file.path('C:', 'Users', 'jorn', 'OneDrive', 'Uni biologie jaar 7', 'AFI thesis', 'Collin_Jorn', 'Collin_Jorn_available data.xlsx')

## upload the data frame in R studio
cj <- read_excel(file.path(onedrive),
                 # sheet= 1,
                 col_names=T,
                 col_types='text',
                 na = '') %>% 
  ## removing special characters
  setNames(tolower(names(.))) %>%         ## removing capital letters in the headings
  setNames(gsub(' ', '', names(.))) %>%   ## removing white spaces in the headings
  setNames(gsub('\\=|\\(|\\)|\\,|\\%|\\/', '', names(.))) %>%    ## removing special characters
  
  ## removing empty rows
  filter(!is.na(sample_nr))
```


```{r setup, include=FALSE}
## adding columns for the locations, one column for the total catching date and one for length class
cj1 <- cj %>%
  mutate(
    location = tolower(location),
    place = structure(NA, class= 'character'),
    place = ifelse(grepl('k', location), 'katerstede', place),
    place = ifelse(grepl('h', location), 'hurwenen'  , place),
## different habitats
    habitat = structure(NA, class= 'character'),
    habitat = ifelse(grepl('^[a-z]{2}', location), 'groyne field', habitat), ## check this one, it is currently not working good!!
    habitat = ifelse(grepl('^h02$|^h05$|^h02$', location), 'stagnant water', habitat),
    habitat = ifelse(grepl('^k07$|^k12$|^k14$', location), 'stagnant water', habitat),
    habitat = ifelse(grepl('^h08$|^h15$', location), 'flowing water', habitat),
    habitat = ifelse(grepl('^k01$|^k10$', location), 'flowing water', habitat),
  ) %>% 
  mutate_at(vars(matches("per|cm|^day$|^week$|^month$|^year|^control$")),funs(as.numeric)) %>% 
  unite(date, c('day','month','year'), sep='-', remove=F) %>% 
  mutate(
    date = as.Date(date, format = "%d-%m-%Y"),
    length_class = structure(NA, class= 'character'),
    length_class = cut(lt_cm, seq(0, 20, 1)),
  )


## making the columns of the food into rows, easier to make graphs with
cj2 <- cj1 %>% 
# group_by(location ,species, date) %>% 
  gather(value = 'percentage', key= 'food', c(17:55)) %>% 
  mutate(
    percentage = ifelse(is.na(percentage), 0, percentage)
  )

## colours
mydiet               <- c(
  'not identifable_per', 'unidentified_per',
  "diatomes_per", 'draadalg_per', 'algae_per', 'aufwuchs_per', 'dead_leaves_branches_per', 'seeds_plants_per',
  'dipter_adult_per', 'chironimidae_adult_per', 'coleoptera_adult_per', 'insect_larvae_per' , 'chaoberus_per', 'insect_adult_terrestial_per', 'trichoptera_per', 'meat_per',
  'chironimidae_larve_per' , 'chaoburus_larvae_per' ,'insect_larve_per', ' ephemeroptera_larvae_per',
  'annelida_per', 'platyhelminthes_per', 'nematomorpha_per' ,
  'cladocera_daphnia_per', 'cladocera_alona_per', 'cladocera_chydorus_per', 'cladocera_bosmina_per','cladocera_ostrocoda_per','cladocera_per', 'acantholeberis_curvirostris_per',
  'mysidae_per', 'carino_gammarus_roeseli_per', 'amphipoda_per',
  'calanoida_copepoda_per','cyclopoida_copepoda_per' , 'roeidiertje_per',
  'bivalvia_per', 'gastropoda_perplanoridae_per',
  'fisher_per')
mydietColors         <-colorRampPalette(RColorBrewer::brewer.pal(39, 'Set1'))
names(mydietColors)  <-levels(as.numeric(mydiet))


```

# ===================================================================================================================
# Graphs
# =================================================================================================================== 

# -------------------------------------------------------------------------------------------------------------------
# Nase
# ===================================================================================================================

# -------------------------------------------------------------------------------------------------------------------
# length distribution 
# -------------------------------------------------------------------------------------------------------------------

```{r setup, include=FALSE}
## making a short summary of the data
cj3 <- cj2 %>%
  # filter(
  # species == 'Wi',
  # place == 'hurwenen',
  # ) %>% 
  # filter(species == 'Sn') %>% 
  group_by(food, species, length_class) %>% 
  dplyr::summarise(mean = mean(percentage))

## making a label for geom_text to know the number of fish per classes 
label <- cj1 %>%
  filter(species == 'Sn') %>% 
  group_by(length_class) %>% 
  summarise(
    label = sum(!is.na(length_class)),
  )

## percentage of all diet 
cj3 %>% 
  filter(!mean == 0) %>%
  filter(species == 'Sn') %>% 
  ggplot()+
  geom_col(
    aes(x=length_class, y=mean, fill=food)
    )+
  geom_text(
    data=label, 
    aes(label = paste("n=", label), 
        y = 80, x= length_class,
        vjust=0, hjust=0), 
    colour="gray15"
    )+
  theme_bw()+
  scale_colour_manual(name = "diet",values = get("mydietColors")) +
```


# -------------------------------------------------------------------------------------------------------------------
# different place
# -------------------------------------------------------------------------------------------------------------------
```{r setup, include=FALSE}
## making a short summary of the data for the group place
cj3 <- cj2 %>%
  # filter(
  # species == 'Wi',
  # place == 'hurwenen',
  # ) %>% 
  # filter(species == 'Sn') %>% 
  group_by(food, species, place) %>%
  dplyr::summarise(mean = mean(percentage))


## making a label for geom_text to know the number of fish per classes 
label <- cj1 %>%
  filter(species == 'Sn') %>% 
  group_by(place) %>% 
  summarise(
    label = sum(!is.na(location)),
  )

## percentage of all diet   
cj3 %>% 
  filter(!mean == 0) %>%
  filter(species == 'Sn') %>% 
  ggplot()+
  geom_col(
    aes(x=place, y=mean, fill=food)
  )+
  geom_text(
    data=label, 
    aes(label = paste("n=", label), 
        y = 80, x= place,
        vjust=0, hjust=0), 
    colour="gray15"
  )+
  theme_bw()
```


# -------------------------------------------------------------------------------------------------------------------
# different location
# -------------------------------------------------------------------------------------------------------------------

```{r setup, include=FALSE}
## making a short summary of the data for the group place
cj3 <- cj2 %>%
  # filter(
  # species == 'Wi',
  # place == 'hurwenen',
  # ) %>% 
  # filter(species == 'Sn') %>% 
  group_by(food, species, location) %>%
  dplyr::summarise(mean = mean(percentage))


## making a label for geom_text to know the number of fish per classes 
label <- cj1 %>%
  filter(species == 'Sn') %>% 
  group_by(location) %>% 
  summarise(
    label = sum(!is.na(location)),
  )

## percentage of all diet   
cj3 %>% 
  filter(!mean == 0) %>%
  filter(species == 'Sn') %>% 
  ggplot()+
  geom_col(
    aes(x=location, y=mean, fill=food)
  )+
  geom_text(
    data=label, 
    aes(label = paste("n=", label), 
        y = 80, x= location,
        vjust=0, hjust=0), 
    colour="gray15"
  )+
  theme_bw()
```


# ===================================================================================================================
# Asp
# ===================================================================================================================

# -------------------------------------------------------------------------------------------------------------------
# length distribution 
# -------------------------------------------------------------------------------------------------------------------

```{r setup, include=FALSE}
## making a short summary of the data
cj3 <- cj2 %>%
  # filter(
  # species == 'Wi',
  # place == 'hurwenen',
  # ) %>% 
  # filter(species == 'Sn') %>% 
  group_by(food, species, length_class) %>%
  dplyr::summarise(mean = mean(percentage))


## making a label for geom_text to know the number of fish per classes 
label <- cj1 %>%
  filter(species == 'Rb') %>% 
  group_by(length_class) %>% 
  summarise(
    label = sum(!is.na(length_class)),
  )

## percentage of all diet 
cj3 %>% 
  filter(!mean == 0) %>%
  filter(species == 'Rb') %>% 
  ggplot()+
  geom_col(
    aes(x=length_class, y=mean, fill=food)
  )+
  geom_text(
    data=label, 
    aes(label = paste("n=", label), 
        y = 80, x= length_class,
        vjust=0, hjust=0), 
    colour="gray15"
  )+
  theme_bw()
```


# -------------------------------------------------------------------------------------------------------------------
# different place
# -------------------------------------------------------------------------------------------------------------------

```{r setup, include=FALSE}
## making a short summary of the data for the group place
cj3 <- cj2 %>%
  # filter(
  # species == 'Wi',
  # place == 'hurwenen',
  # ) %>% 
  # filter(species == 'Rb') %>% 
  group_by(food, species, place) %>%
  dplyr::summarise(mean = mean(percentage))


## making a label for geom_text to know the number of fish per classes 
label <- cj1 %>%
  filter(species == 'Rb') %>% 
  group_by(place) %>% 
  summarise(
    label = sum(!is.na(location)),
  )

## percentage of all diet   
cj3 %>% 
  filter(!mean == 0) %>%
  filter(species == 'Rb') %>% 
  ggplot()+
  geom_col(
    aes(x=place, y=mean, fill=food)
  )+
  geom_text(
    data=label, 
    aes(label = paste("n=", label), 
        y = 80, x= place,
        vjust=0, hjust=0), 
    colour="gray15"
  )+
  theme_bw()
```

# -------------------------------------------------------------------------------------------------------------------
# different location
# -------------------------------------------------------------------------------------------------------------------

```{r setup, include=FALSE}
## making a short summary of the data for the group place
cj3 <- cj2 %>%
  # filter(
  # species == 'Wi',
  # place == 'hurwenen',
  # ) %>% 
  # filter(species == 'Rb') %>% 
  group_by(food, species, location) %>%
  dplyr::summarise(mean = mean(percentage))


## making a label for geom_text to know the number of fish per classes 
label <- cj1 %>%
  filter(species == 'Rb') %>% 
  group_by(location) %>% 
  summarise(
    label = sum(!is.na(location)),
  )

## percentage of all diet   
cj3 %>% 
  filter(!mean == 0) %>%
  filter(species == 'Rb') %>% 
  ggplot()+
  geom_col(
    aes(x=location, y=mean, fill=food)
  )+
  geom_text(
    data=label, 
    aes(label = paste("n=", label), 
        y = 80, x= location,
        vjust=0, hjust=0), 
    colour="gray15"
  )+
  theme_bw()
```

# ===================================================================================================================
# Ide
# ===================================================================================================================

# -------------------------------------------------------------------------------------------------------------------
# length distribution 
# -------------------------------------------------------------------------------------------------------------------

```{r setup, include=FALSE}
## making a short summary of the data
cj3 <- cj2 %>%
  # filter(
  # species == 'Wi',
  # place == 'hurwenen',
  # ) %>% 
  # filter(species == 'Sn') %>% 
  group_by(food, species, length_class) %>%
  dplyr::summarise(mean = mean(percentage))


## making a label for geom_text to know the number of fish per classes 
label <- cj1 %>%
  filter(species == 'Wi') %>% 
  group_by(length_class) %>% 
  summarise(
    label = sum(!is.na(length_class)),
  )

## percentage of all diet 
cj3 %>% 
  filter(!mean == 0) %>%
  filter(species == 'Wi') %>% 
  ggplot()+
  geom_col(
    aes(x=length_class, y=mean, fill=food)
  )+
  geom_text(
    data=label, 
    aes(label = paste("n=", label), 
        y = 80, x= length_class,
        vjust=0, hjust=0), 
    colour="gray15"
  )+
  theme_bw()
```

# -------------------------------------------------------------------------------------------------------------------
# different place
# -------------------------------------------------------------------------------------------------------------------

```{r setup, include=FALSE}
## making a short summary of the data for the group place
cj3 <- cj2 %>%
  # filter(
  # species == 'Wi',
  # place == 'hurwenen',
  # ) %>% 
  # filter(species == 'Wi') %>% 
  group_by(food, species, place) %>%
  dplyr::summarise(mean = mean(percentage))


## making a label for geom_text to know the number of fish per classes 
label <- cj1 %>%
  filter(species == 'Wi') %>% 
  group_by(place) %>% 
  summarise(
    label = sum(!is.na(location)),
  )

## percentage of all diet   
cj3 %>% 
  filter(!mean == 0) %>%
  filter(species == 'Wi') %>% 
  ggplot()+
  geom_col(
    aes(x=place, y=mean, fill=food)
  )+
  geom_text(
    data=label, 
    aes(label = paste("n=", label), 
        y = 80, x= place,
        vjust=0, hjust=0), 
    colour="gray15"
  )+
  theme_bw()
```

# -------------------------------------------------------------------------------------------------------------------
# different location
# -------------------------------------------------------------------------------------------------------------------
```{r setup, include=FALSE}
## making a short summary of the data for the group place
cj3 <- cj2 %>%
  # filter(
  # species == 'Wi',
  # place == 'hurwenen',
  # ) %>% 
  # filter(species == 'Wi') %>% 
  group_by(food, species, location) %>%
  dplyr::summarise(mean = mean(percentage))


## making a label for geom_text to know the number of fish per classes 
label <- cj1 %>%
  filter(species == 'Wi') %>% 
  group_by(location) %>% 
  summarise(
    label = sum(!is.na(location)),
  )

## percentage of all diet   
cj3 %>% 
  filter(!mean == 0) %>%
  filter(species == 'Wi') %>% 
  ggplot()+
  geom_col(
    aes(x=location, y=mean, fill=food)
  )+
  geom_text(
    data=label, 
    aes(label = paste("n=", label), 
        y = 80, x= location,
        vjust=0, hjust=0), 
    colour="gray15"
  )+
  theme_bw()
```